language: node_js

node_js:
  - "lts/*"
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - "yarn test:coverage"
  - "yarn codecov"
  - "yarn build"

notifications:
  email:
    - ram@hiddentao.com
